name: CI

on: [push]

jobs:
  linux-job:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - name: Download source code
        uses: actions/checkout@v2
      - name: Format
        run: "crystal tool format --check"
      - name: Lint
        run: "shards install; bin/ameba"
      - name: Run tests
        run: "crystal spec --warnings all --error-on-warnings"
      - name: Build
        run: "shards build"
